from __future__ import unicode_literals

import os

from PyPDF2 import PdfFileWriter

import capkpi
from capkpi import _
from capkpi.core.doctype.access_log.access_log import make_access_log
from capkpi.utils.pdf import cleanup, get_pdf
from capkpi.www.printview import validate_print_permission

no_cache = 1

base_template_path = "templates/www/printview.html"
standard_format = "templates/print_formats/standard.html"


@capkpi.whitelist()
def download_multi_pdf(doctype, name, format=None, no_letterhead=False, options=None):
	"""
	Concatenate multiple docs as PDF .

	Returns a PDF compiled by concatenating multiple documents. The documents
	can be from a single DocType or multiple DocTypes

	Note: The design may seem a little weird, but it exists exists to
	        ensure backward compatibility. The correct way to use this function is to
	        pass a dict to doctype as described below

	NEW FUNCTIONALITY
	=================
	Parameters:
	doctype (dict):
	        key (string): DocType name
	        value (list): of strings of doc names which need to be concatenated and printed
	name (string):
	        name of the pdf which is generated
	format:
	        Print Format to be used

	Returns:
	PDF: A PDF generated by the concatenation of the mentioned input docs

	OLD FUNCTIONALITY - soon to be deprecated
	=========================================
	Parameters:
	doctype (string):
	        name of the DocType to which the docs belong which need to be printed
	name (string or list):
	        If string the name of the doc which needs to be printed
	        If list the list of strings of doc names which needs to be printed
	format:
	        Print Format to be used

	Returns:
	PDF: A PDF generated by the concatenation of the mentioned input docs
	"""

	import json

	output = PdfFileWriter()

	if isinstance(options, str):
		options = json.loads(options)

	if not isinstance(doctype, dict):
		result = json.loads(name)

		# Concatenating pdf files
		for i, ss in enumerate(result):
			output = capkpi.get_print(
				doctype,
				ss,
				format,
				as_pdf=True,
				output=output,
				no_letterhead=no_letterhead,
				pdf_options=options,
			)
		capkpi.local.response.filename = "{doctype}.pdf".format(
			doctype=doctype.replace(" ", "-").replace("/", "-")
		)
	else:
		for doctype_name in doctype:
			for doc_name in doctype[doctype_name]:
				try:
					output = capkpi.get_print(
						doctype_name,
						doc_name,
						format,
						as_pdf=True,
						output=output,
						no_letterhead=no_letterhead,
						pdf_options=options,
					)
				except Exception:
					capkpi.log_error("Permission Error on doc {} of doctype {}".format(doc_name, doctype_name))
		capkpi.local.response.filename = "{}.pdf".format(name)

	capkpi.local.response.filecontent = read_multi_pdf(output)
	capkpi.local.response.type = "download"


def read_multi_pdf(output):
	# Get the content of the merged pdf files
	fname = os.path.join("/tmp", "capkpi-pdf-{0}.pdf".format(capkpi.generate_hash()))
	output.write(open(fname, "wb"))

	with open(fname, "rb") as fileobj:
		filedata = fileobj.read()

	return filedata


@capkpi.whitelist(allow_guest=True)
def download_pdf(doctype, name, format=None, doc=None, no_letterhead=0):
	doc = doc or capkpi.get_doc(doctype, name)
	try:
		validate_print_permission(doc)
	except capkpi.exceptions.LinkExpired:
		capkpi.local.response.http_status_code = 410
		capkpi.local.response.message = _("Link Expired")
		return
	except capkpi.exceptions.InvalidKeyError:
		capkpi.local.response.http_status_code = 401
		capkpi.local.response.message = _("Invalid Key")
		return

	html = capkpi.get_print(doctype, name, format, doc=doc, no_letterhead=no_letterhead)
	capkpi.local.response.filename = "{name}.pdf".format(
		name=name.replace(" ", "-").replace("/", "-")
	)
	capkpi.local.response.filecontent = get_pdf(html)
	capkpi.local.response.type = "pdf"


@capkpi.whitelist()
def report_to_pdf(html, orientation="Landscape"):
	make_access_log(file_type="PDF", method="PDF", page=html)
	capkpi.local.response.filename = "report.pdf"
	capkpi.local.response.filecontent = get_pdf(html, {"orientation": orientation})
	capkpi.local.response.type = "pdf"


@capkpi.whitelist()
def print_by_server(
	doctype, name, printer_setting, print_format=None, doc=None, no_letterhead=0, file_path=None
):
	print_settings = capkpi.get_doc("Network Printer Settings", printer_setting)
	try:
		import cups
	except ImportError:
		capkpi.throw(_("You need to install pycups to use this feature!"))

	try:
		cups.setServer(print_settings.server_ip)
		cups.setPort(print_settings.port)
		conn = cups.Connection()
		output = PdfFileWriter()
		output = capkpi.get_print(
			doctype, name, print_format, doc=doc, no_letterhead=no_letterhead, as_pdf=True, output=output
		)
		if not file_path:
			file_path = os.path.join("/", "tmp", "capkpi-pdf-{0}.pdf".format(capkpi.generate_hash()))
		output.write(open(file_path, "wb"))
		conn.printFile(print_settings.printer_name, file_path, name, {})
	except IOError as e:
		if (
			"ContentNotFoundError" in e.message
			or "ContentOperationNotPermittedError" in e.message
			or "UnknownContentError" in e.message
			or "RemoteHostClosedError" in e.message
		):
			capkpi.throw(_("PDF generation failed"))
	except cups.IPPError:
		capkpi.throw(_("Printing failed"))
	finally:
		return
